version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-sdtin 123456789012.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - docker build -t reservations -f ./apps/reservations/Dockerfile .
      - docker tag reservations:latest 123456789012.dkr.ecr.us-east-2.amazonaws.com/reservations:latest

      - docker build -t auth -f ./apps/auth/Dockerfile .
      - docker tag auth:latest 123456789012.dkr.ecr.us-east-2.amazonaws.com/auth:latest

      - docker build -t payments -f ./apps/payments/Dockerfile .
      - docker tag payments:latest 123456789012.dkr.ecr.us-east-2.amazonaws.com/payments:latest

      - docker build -t notifications -f ./apps/notifications/Dockerfile .
      - docker tag notifications:latest 123456789012.dkr.ecr.us-east-2.amazonaws.com/notifications:latest
  post_build:
    commands:
      - docker push 123456789012.dkr.ecr.us-east-2.amazonaws.com/reservations:latest
      - docker push 123456789012.dkr.ecr.us-east-2.amazonaws.com/auth:latest
      - docker push 123456789012.dkr.ecr.us-east-2.amazonaws.com/payments:latest
      - docker push 123456789012.dkr.ecr.us-east-2.amazonaws.com/notifications:latest
